- hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python

  roles:
    - docker      # installe Docker (si pas déjà installé)
    - network     # crée le réseau myapp_network
    - database    # ensuite lance Postgres dans le réseau
    - app         # ensuite lance l’API
    - proxy       # et enfin le proxy http
