---
# roles/proxy/tasks/main.yml

- name: Créer un dossier temporaire pour le httpd.conf sur la VM
  file:
    path: /home/admin/httpd_conf
    state: directory
    owner: admin
    group: admin
    mode: 0755

- name: Copier le httpd.conf personnalisé sur la VM
  copy:
    src: httpd.conf
    dest: /home/admin/httpd_conf/httpd.conf
    owner: admin
    group: admin
    mode: 0644

- name: Lancer le conteneur httpd en montant le httpd.conf
  docker_container:
    name: httpd
    image: httpd:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    networks:
      - name: myapp_network
    volumes:
      # Montre le fichier host vers l'intérieur du conteneur
      - /home/admin/httpd_conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
