- name: Launch PostgreSQL container
  docker_container:
    name: my_postgres
    image: postgres:15
    env:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    networks:
      - name: myapp_network
    state: started
    restart_policy: always
  vars:
    ansible_python_interpreter: /usr/bin/python3
