- name: Lancer PostgreSQL
  docker_container:
    name: my_postgres_db
    image: postgres:15
    env:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: user
      POSTGRES_DB: mydb
    state: started
    restart_policy: always
    networks:
      - name: myapp_network
