name: CD - Deploy on image update

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client and Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client ansible

      - name: Copy private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible
        run: |
          ansible-playbook -i inventories/setup.yml site.yml --ssh-extra-args="-o StrictHostKeyChecking=no"

